ticket_dir_50kb: /juno/work/shah/users/weinera2/projects/hmmcopy/output
ticket_dir_500kb: /work/shah/tantalus
datasets: ['2295', 'SA039']
fitness_datasets: ['SA000', 'SA001', 'SA039U', 'SA532', 'SA609',
                   'SA609X3X8a', 'SA906a', 'SA906b', 'SA1035U',
                   'SA1035T', 'SA535_CISPLATIN_CombinedU', 'SA535_CISPLATIN_CombinedT']
fitness_rx_pairs:
  SA1035:
    Rx: 'SA1035T'
    UnRx: 'SA1035U'
  SA535:
    Rx: 'SA535_CISPLATIN_CombinedT'
    UnRx: 'SA535_CISPLATIN_CombinedU'
signatures_datasets: ['SA039', 'SA906a', 'SA906b', 'SA1188', 'SA1054', 'SA1055', 'SA1056', '2295']
simulated_datasets:
  # fully diploid datasets
  D1:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A']
    clone_probs: [1]
    states: [2]
    state_probs: [1]
    cell_CNA_prob: 0
  # polyclonal datasets
  P1:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A', 'B', 'C']
    clone_probs: [0.4, 0.3, 0.3]
    states: [1, 2, 3, 4, 5, 6, 7]
    state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
    cell_CNA_prob: 0.05

