ticket_dir_50kb: /juno/work/shah/users/weinera2/projects/hmmcopy/output
ticket_dir_500kb: /work/shah/tantalus
fitness_datasets: ['SA000', 'SA001', 'SA039U', 'SA532', 'SA609',
                   'SA609X3X8a', 'SA906a', 'SA906b', 'SA1035U',
                   'SA1035T', 'SA535_CISPLATIN_CombinedU', 'SA535_CISPLATIN_CombinedT']
fitness_rx_pairs:
  SA1035:
    Rx: 'SA1035T'
    UnRx: 'SA1035U'
  SA535:
    Rx: 'SA535_CISPLATIN_CombinedT'
    UnRx: 'SA535_CISPLATIN_CombinedU'
permuted_datasets:
  A:
    rate: 0.01
  B:
    rate: 0.01
  C:
    rate: 0.01
  D:
    rate: 0.03
  E:
    rate: 0.03
  F:
    rate: 0.03
  G:
    rate: 0.05
  H:
    rate: 0.05
  I:
    rate: 0.05
  J:
    rate: 0.1
  K:
    rate: 0.1
  L:
    rate: 0.1
  M:
    rate: 0.2
  N:
    rate: 0.2
  O:
    rate: 0.2
  P:
    rate: 0.3
  Q:
    rate: 0.3
  R:
    rate: 0.3
  S:
    rate: 0.5
  T:
    rate: 0.5
  U:
    rate: 0.5
  V:
    rate: 0.75
  W:
    rate: 0.75
  X:
    rate: 0.75
signatures_cell_lines:
  SA039:
    type: 'hTERT,WT'
  SA906a:
    type: 'hTERT,TP53-/-'
  SA906b:
    type: 'hTERT,TP53-/-'
  SA1188:
    type: 'hTERT,BRCA2+/−,TP53−/−'
  SA1056:
    type: 'hTERT,BRCA2−/−,TP53−/−'
  SA1055:
    type: 'hTERT,BRCA2−/−,TP53−/−'
  SA1054:
    type: 'hTERT,BRCA1−/−,TP53−/−'
  SA1292:
    type: 'hTERT,BRCA1+/−,TP53−/−'
  OV2295:
    type: 'HGSOC-line'
signatures_patient_tumors:
  SA1091:
    type: 'HGSOC'
    signature: 'FBI'
  # SA1047:
  #   type: 'HGSOC'
  #   signature: 'TD'
  SA1093:
    type: 'HGSOC'
    signature: 'TD'
  SA1049:
    type: 'HGSOC'
    signature: 'FBI'
  SA1096:
    type: 'HGSOC'
    signature: 'FBI'
  # SA1162:
  #   type: 'HGSOC'
  #   signature: 'FBI'
  SA1050:
    type: 'HGSOC'
    signature: 'HRD-Dup'
  SA1051:
    type: 'HGSOC'
    signature: 'HRD-Dup'
  SA1052:
    type: 'HGSOC'
    signature: 'HRD-Dup'
  SA1053:
    type: 'HGSOC'
    signature: 'HRD-Dup'
  SA1181:
    type: 'HGSOC'
    signature: 'HRD-Dup'
  SA1182:
    type: 'HGSOC'
    signature: 'FBI'
  SA1184:
    type: 'HGSOC'
    signature: 'HRD-Dup'
  SA530:
    type: 'TNBC'
    signature: 'FBI'
  SA604:
    type: 'TNBC'
    signature: 'FBI'
  # SA609:
  #   type: 'TNBC'
  #   signature: 'FBI'
  SA501:
    type: 'TNBC'
    signature: 'HRD-Dup'
  # SA535:
  #   type: 'TNBC'
  #   signature: 'HRD-Dup'
simulated_datasets:
  # fully diploid datasets
  D1:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A']
    clone_probs: [1]
    states: [2]
    state_probs: [1]
    cell_CNA_prob: 0
  D2:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 5
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A']
    clone_probs: [1]
    states: [2]
    state_probs: [1]
    cell_CNA_prob: 0
  D3:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 15
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A']
    clone_probs: [1]
    states: [2]
    state_probs: [1]
    cell_CNA_prob: 0
  D4:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [0.1, 0.2, -1, 1, -0.25]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A']
    clone_probs: [1]
    states: [2]
    state_probs: [1]
    cell_CNA_prob: 0
  D5:
    nb_r: 10000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A']
    clone_probs: [1]
    states: [2]
    state_probs: [1]
    cell_CNA_prob: 0
  D6:
    nb_r: 1000000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A']
    clone_probs: [1]
    states: [2]
    state_probs: [1]
    cell_CNA_prob: 0
  # test effect of cell-specific CNAs in diploid background
  D7:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A']
    clone_probs: [1]
    states: [1, 2, 3, 4, 5, 6]
    state_probs: [0.02, 0.95, 0.01, 0.01, 0.005, 0.005]
    cell_CNA_prob: 0.02
  D8:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A']
    clone_probs: [1]
    states: [1, 2, 3, 4, 5, 6]
    state_probs: [0.02, 0.95, 0.01, 0.01, 0.005, 0.005]
    cell_CNA_prob: 0.05
  # polyclonal datasets
  P1:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A', 'B', 'C']
    clone_probs: [0.4, 0.3, 0.3]
    states: [1, 2, 3, 4, 5, 6, 7]
    state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
    cell_CNA_prob: 0.00
  P2:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A', 'B', 'C']
    clone_probs: [0.4, 0.3, 0.3]
    states: [1, 2, 3, 4, 5, 6, 7]
    state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
    cell_CNA_prob: 0.02
  P3:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 10
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A', 'B', 'C']
    clone_probs: [0.4, 0.3, 0.3]
    states: [1, 2, 3, 4, 5, 6, 7]
    state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
    cell_CNA_prob: 0.05
  P4:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 5
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A', 'B', 'C']
    clone_probs: [0.4, 0.3, 0.3]
    states: [1, 2, 3, 4, 5, 6, 7]
    state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
    cell_CNA_prob: 0.00
  P5:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 5
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A', 'B', 'C']
    clone_probs: [0.4, 0.3, 0.3]
    states: [1, 2, 3, 4, 5, 6, 7]
    state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
    cell_CNA_prob: 0.02
  P6:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 5
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A', 'B', 'C']
    clone_probs: [0.4, 0.3, 0.3]
    states: [1, 2, 3, 4, 5, 6, 7]
    state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
    cell_CNA_prob: 0.05
  P7:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 15
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A', 'B', 'C']
    clone_probs: [0.4, 0.3, 0.3]
    states: [1, 2, 3, 4, 5, 6, 7]
    state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
    cell_CNA_prob: 0.00
  P8:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 15
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A', 'B', 'C']
    clone_probs: [0.4, 0.3, 0.3]
    states: [1, 2, 3, 4, 5, 6, 7]
    state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
    cell_CNA_prob: 0.02
  P9:
    nb_r: 100000
    gc_col: 'gc'
    gc_betas: [1.2, 0.0]
    rt_col: 'mcf7rt'
    A: 15
    num_reads: 1000000
    num_cells_S: 400
    num_cells_G: 400
    bin_size: 500000
    clones: ['A', 'B', 'C']
    clone_probs: [0.4, 0.3, 0.3]
    states: [1, 2, 3, 4, 5, 6, 7]
    state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
    cell_CNA_prob: 0.05


