ticket_dir_50kb: /juno/work/shah/users/weinera2/projects/hmmcopy/output
ticket_dir_500kb: /work/shah/tantalus
datasets: ['2295', 'SA039']
fitness_datasets: ['SA000', 'SA001', 'SA039U', 'SA532', 'SA609',
                   'SA609X3X8a', 'SA906a', 'SA906b', 'SA1035U',
                   'SA1035T', 'SA535_CISPLATIN_CombinedU', 'SA535_CISPLATIN_CombinedT']
fitness_rx_pairs:
  SA1035:
    Rx: 'SA1035T'
    UnRx: 'SA1035U'
  SA535:
    Rx: 'SA535_CISPLATIN_CombinedT'
    UnRx: 'SA535_CISPLATIN_CombinedU'
simulated_datasets:
  diploid:
    A1:
      sigma1: 0.3
      gc_slope: 1.2
      gc_int: 0.0
      A: 0.1
      B: 0.0
      num_reads: 1000000
      num_cells_S: 400
      num_cells_G: 400
      bin_size: 500000
      s_time_stdev: -1  # uniform
    A2:
      sigma1: 0.3
      gc_slope: 1.2
      gc_int: 0.0
      A: 0.5
      B: 0.0
      num_reads: 1000000
      num_cells_S: 400
      num_cells_G: 400
      bin_size: 500000
      s_time_stdev: -1  # uniform
    A3:
      sigma1: 0.3
      gc_slope: 1.2
      gc_int: 0.0
      A: 1.0
      B: 0.0
      num_reads: 1000000
      num_cells_S: 400
      num_cells_G: 400
      bin_size: 500000
      s_time_stdev: -1  # uniform
    A4:
      sigma1: 0.3
      gc_slope: 1.2
      gc_int: 0.0
      A: 0.05
      B: 0.0
      num_reads: 1000000
      num_cells_S: 400
      num_cells_G: 400
      bin_size: 500000
      s_time_stdev: -1  # uniform
    A5:
      sigma1: 0.3
      gc_slope: 1.2
      gc_int: 0.0
      A: 0.1
      B: 0.0
      num_reads: 1000000
      num_cells_S: 400
      num_cells_G: 400
      bin_size: 500000
      s_time_stdev: 30  # normal
    A6:
      sigma1: 0.3
      gc_slope: 1.2
      gc_int: 0.0
      A: 0.1
      B: 0.0
      num_reads: 1000000
      num_cells_S: 400
      num_cells_G: 400
      bin_size: 500000
      s_time_stdev: 20  # normal
    A7:
      sigma1: 0.3
      gc_slope: 1.2
      gc_int: 0.0
      A: 0.1
      B: 0.0
      num_reads: 1000000
      num_cells_S: 400
      num_cells_G: 400
      bin_size: 500000
      s_time_stdev: 10  # normal
    A8:
      sigma1: 0.3
      gc_slope: 1.2
      gc_int: 0.0
      A: 0.1
      B: 0.0
      num_reads: 1000000
      num_cells_S: 400
      num_cells_G: 400
      bin_size: 50000
      s_time_stdev: -1  # uniform
  polyploid:
    P1:
      sigma1: 0.3
      gc_slope: 1.2
      gc_int: 0.0
      A: 0.1
      B: 0.0
      num_reads: 1000000
      num_cells_S: 400
      num_cells_G: 400
      bin_size: 500000
      s_time_stdev: -1  # uniform
      clones: ['A', 'B', 'C']
      clone_probs: [0.4, 0.3, 0.3]
      states: [1, 2, 3, 4, 5, 6, 7]
      state_probs: [0.06, 0.8, 0.05, 0.03, 0.02, 0.02, 0.02]
      cell_CNA_prob: 0.05
    P2:
      sigma1: 0.3
      gc_slope: 1.2
      gc_int: 0.0
      A: 0.1
      B: 0.0
      num_reads: 1000000
      num_cells_S: 400
      num_cells_G: 400
      bin_size: 500000
      s_time_stdev: -1  # uniform
      clones: ['A']
      clone_probs: [1]
      states: [2]
      state_probs: [1]
      cell_CNA_prob: 0

